# Generated by Django 4.2 on 2025-01-22 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("TEXT_INPUT_MEMORY", "Fill in the gaps from memory"),
                            ("CHOICE_QUESTIONS", "Multiple choice questions"),
                            ("MULTIPLE_CHOICE", "Multiple correct answers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "display_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DROPDOWN", "Single dropdown with all options"),
                            ("RADIO", "Individual radio buttons"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "word_list",
                    models.TextField(
                        blank=True,
                        help_text="Available words for TEXT_INPUT_WORDLIST type. Separate words with commas.",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("correct_answer", models.TextField()),
                ("available_words", models.TextField(blank=True, null=True)),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_builder.test",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("is_correct", models.BooleanField(default=False)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz_builder.question",
                    ),
                ),
            ],
        ),
    ]
